
// WARNING: generated by dump_visitor_keys.mjs, do not edit directly

// babel changed the order at some version, but we need to keep the old one for now
export const VISITOR_KEYS = {
  "ArrayExpression": [
    "elements"
  ],
  "AssignmentExpression": [
    "left",
    "right"
  ],
  "BinaryExpression": [
    "left",
    "right"
  ],
  "InterpreterDirective": [],
  "Directive": [
    "value"
  ],
  "DirectiveLiteral": [],
  "BlockStatement": [
    "directives",
    "body"
  ],
  "BreakStatement": [
    "label"
  ],
  "CallExpression": [
    "callee",
    "arguments",
    "typeParameters",
    "typeArguments"
  ],
  "CatchClause": [
    "param",
    "body"
  ],
  "ConditionalExpression": [
    "test",
    "consequent",
    "alternate"
  ],
  "ContinueStatement": [
    "label"
  ],
  "DebuggerStatement": [],
  "DoWhileStatement": [
    "test",
    "body"
  ],
  "EmptyStatement": [],
  "ExpressionStatement": [
    "expression"
  ],
  "File": [
    "program"
  ],
  "ForInStatement": [
    "left",
    "right",
    "body"
  ],
  "ForStatement": [
    "init",
    "test",
    "update",
    "body"
  ],
  "FunctionDeclaration": [
    "id",
    "typeParameters",
    "params",
    "returnType",
    "body"
  ],
  "FunctionExpression": [
    "id",
    "typeParameters",
    "params",
    "returnType",
    "body"
  ],
  "Identifier": [
    "typeAnnotation",
    "decorators"
  ],
  "IfStatement": [
    "test",
    "consequent",
    "alternate"
  ],
  "LabeledStatement": [
    "label",
    "body"
  ],
  "StringLiteral": [],
  "NumericLiteral": [],
  "NullLiteral": [],
  "BooleanLiteral": [],
  "RegExpLiteral": [],
  "LogicalExpression": [
    "left",
    "right"
  ],
  "MemberExpression": [
    "object",
    "property"
  ],
  "NewExpression": [
    "callee",
    "arguments",
    "typeParameters",
    "typeArguments"
  ],
  "Program": [
    "directives",
    "body"
  ],
  "ObjectExpression": [
    "properties"
  ],
  "ObjectMethod": [
    "decorators",
    "key",
    "typeParameters",
    "params",
    "returnType",
    "body"
  ],
  "ObjectProperty": [
    "key",
    "value",
    "decorators"
  ],
  "RestElement": [
    "argument",
    "typeAnnotation"
  ],
  "ReturnStatement": [
    "argument"
  ],
  "SequenceExpression": [
    "expressions"
  ],
  "ParenthesizedExpression": [
    "expression"
  ],
  "SwitchCase": [
    "test",
    "consequent"
  ],
  "SwitchStatement": [
    "discriminant",
    "cases"
  ],
  "ThisExpression": [],
  "ThrowStatement": [
    "argument"
  ],
  "TryStatement": [
    "block",
    "handler",
    "finalizer"
  ],
  "UnaryExpression": [
    "argument"
  ],
  "UpdateExpression": [
    "argument"
  ],
  "VariableDeclaration": [
    "declarations"
  ],
  "VariableDeclarator": [
    "id",
    "init"
  ],
  "WhileStatement": [
    "test",
    "body"
  ],
  "WithStatement": [
    "object",
    "body"
  ],
  "AssignmentPattern": [
    "left",
    "right",
    "decorators"
  ],
  "ArrayPattern": [
    "elements",
    "typeAnnotation"
  ],
  "ArrowFunctionExpression": [
    "typeParameters",
    "params",
    "returnType",
    "body"
  ],
  "ClassBody": [
    "body"
  ],
  "ClassExpression": [
    "decorators",
    "id",
    "typeParameters",
    "superClass",
    "superTypeParameters",
    "mixins",
    "implements",
    "body"
  ],
  "ClassDeclaration": [
    "decorators",
    "id",
    "typeParameters",
    "superClass",
    "superTypeParameters",
    "mixins",
    "implements",
    "body"
  ],
  "ExportAllDeclaration": [
    "source",
    "attributes",
    "assertions"
  ],
  "ExportDefaultDeclaration": [
    "declaration"
  ],
  "ExportNamedDeclaration": [
    "declaration",
    "specifiers",
    "source",
    "attributes"
  ],
  "ExportSpecifier": [
    "local",
    "exported"
  ],
  "ForOfStatement": [
    "left",
    "right",
    "body"
  ],
  "ImportDeclaration": [
    "specifiers",
    "source",
    "attributes",
    "assertions"
  ],
  "ImportDefaultSpecifier": [
    "local"
  ],
  "ImportNamespaceSpecifier": [
    "local"
  ],
  "ImportSpecifier": [
    "imported",
    "local"
  ],
  "ImportExpression": [
    "source",
    "options"
  ],
  "MetaProperty": [
    "meta",
    "property"
  ],
  "ClassMethod": [
    "decorators",
    "key",
    "typeParameters",
    "params",
    "returnType",
    "body"
  ],
  "ObjectPattern": [
    "properties",
    "typeAnnotation",
    "decorators"
  ],
  "SpreadElement": [
    "argument"
  ],
  "Super": [],
  "TaggedTemplateExpression": [
    "tag",
    "typeParameters",
    "quasi"
  ],
  "TemplateElement": [],
  "TemplateLiteral": [
    "quasis",
    "expressions"
  ],
  "YieldExpression": [
    "argument"
  ],
  "AwaitExpression": [
    "argument"
  ],
  "Import": [],
  "BigIntLiteral": [],
  "ExportNamespaceSpecifier": [
    "exported"
  ],
  "OptionalMemberExpression": [
    "object",
    "property"
  ],
  "OptionalCallExpression": [
    "callee",
    "arguments",
    "typeParameters",
    "typeArguments"
  ],
  "ClassProperty": [
    "decorators",
    "key",
    "typeAnnotation",
    "value"
  ],
  "ClassAccessorProperty": [
    "decorators",
    "key",
    "typeAnnotation",
    "value"
  ],
  "ClassPrivateProperty": [
    "decorators",
    "key",
    "typeAnnotation",
    "value"
  ],
  "ClassPrivateMethod": [
    "decorators",
    "key",
    "typeParameters",
    "params",
    "returnType",
    "body"
  ],
  "PrivateName": [
    "id"
  ],
  "StaticBlock": [
    "body"
  ],
  "AnyTypeAnnotation": [],
  "ArrayTypeAnnotation": [
    "elementType"
  ],
  "BooleanTypeAnnotation": [],
  "BooleanLiteralTypeAnnotation": [],
  "NullLiteralTypeAnnotation": [],
  "ClassImplements": [
    "id",
    "typeParameters"
  ],
  "DeclareClass": [
    "id",
    "typeParameters",
    "extends",
    "mixins",
    "implements",
    "body"
  ],
  "DeclareFunction": [
    "id"
  ],
  "DeclareInterface": [
    "id",
    "typeParameters",
    "extends",
    "body"
  ],
  "DeclareModule": [
    "id",
    "body"
  ],
  "DeclareModuleExports": [
    "typeAnnotation"
  ],
  "DeclareTypeAlias": [
    "id",
    "typeParameters",
    "right"
  ],
  "DeclareOpaqueType": [
    "id",
    "typeParameters",
    "supertype"
  ],
  "DeclareVariable": [
    "id"
  ],
  "DeclareExportDeclaration": [
    "declaration",
    "specifiers",
    "source",
    "attributes"
  ],
  "DeclareExportAllDeclaration": [
    "source",
    "attributes"
  ],
  "DeclaredPredicate": [
    "value"
  ],
  "ExistsTypeAnnotation": [],
  "FunctionTypeAnnotation": [
    "typeParameters",
    "params",
    "rest",
    "returnType"
  ],
  "FunctionTypeParam": [
    "name",
    "typeAnnotation"
  ],
  "GenericTypeAnnotation": [
    "id",
    "typeParameters"
  ],
  "InferredPredicate": [],
  "InterfaceExtends": [
    "id",
    "typeParameters"
  ],
  "InterfaceDeclaration": [
    "id",
    "typeParameters",
    "extends",
    "body"
  ],
  "InterfaceTypeAnnotation": [
    "extends",
    "body"
  ],
  "IntersectionTypeAnnotation": [
    "types"
  ],
  "MixedTypeAnnotation": [],
  "EmptyTypeAnnotation": [],
  "NullableTypeAnnotation": [
    "typeAnnotation"
  ],
  "NumberLiteralTypeAnnotation": [],
  "NumberTypeAnnotation": [],
  "ObjectTypeAnnotation": [
    "properties",
    "indexers",
    "callProperties",
    "internalSlots"
  ],
  "ObjectTypeInternalSlot": [
    "id",
    "value"
  ],
  "ObjectTypeCallProperty": [
    "value"
  ],
  "ObjectTypeIndexer": [
    "variance",
    "id",
    "key",
    "value"
  ],
  "ObjectTypeProperty": [
    "key",
    "value",
    "variance"
  ],
  "ObjectTypeSpreadProperty": [
    "argument"
  ],
  "OpaqueType": [
    "id",
    "typeParameters",
    "supertype",
    "impltype"
  ],
  "QualifiedTypeIdentifier": [
    "qualification",
    "id"
  ],
  "StringLiteralTypeAnnotation": [],
  "StringTypeAnnotation": [],
  "SymbolTypeAnnotation": [],
  "ThisTypeAnnotation": [],
  "TupleTypeAnnotation": [
    "types"
  ],
  "TypeofTypeAnnotation": [
    "argument"
  ],
  "TypeAlias": [
    "id",
    "typeParameters",
    "right"
  ],
  "TypeAnnotation": [
    "typeAnnotation"
  ],
  "TypeCastExpression": [
    "expression",
    "typeAnnotation"
  ],
  "TypeParameter": [
    "bound",
    "default",
    "variance"
  ],
  "TypeParameterDeclaration": [
    "params"
  ],
  "TypeParameterInstantiation": [
    "params"
  ],
  "UnionTypeAnnotation": [
    "types"
  ],
  "Variance": [],
  "VoidTypeAnnotation": [],
  "EnumDeclaration": [
    "id",
    "body"
  ],
  "EnumBooleanBody": [
    "members"
  ],
  "EnumNumberBody": [
    "members"
  ],
  "EnumStringBody": [
    "members"
  ],
  "EnumSymbolBody": [
    "members"
  ],
  "EnumBooleanMember": [
    "id"
  ],
  "EnumNumberMember": [
    "id",
    "init"
  ],
  "EnumStringMember": [
    "id",
    "init"
  ],
  "EnumDefaultedMember": [
    "id"
  ],
  "IndexedAccessType": [
    "objectType",
    "indexType"
  ],
  "OptionalIndexedAccessType": [
    "objectType",
    "indexType"
  ],
  "JSXAttribute": [
    "name",
    "value"
  ],
  "JSXClosingElement": [
    "name"
  ],
  "JSXElement": [
    "openingElement",
    "children",
    "closingElement"
  ],
  "JSXEmptyExpression": [],
  "JSXExpressionContainer": [
    "expression"
  ],
  "JSXSpreadChild": [
    "expression"
  ],
  "JSXIdentifier": [],
  "JSXMemberExpression": [
    "object",
    "property"
  ],
  "JSXNamespacedName": [
    "namespace",
    "name"
  ],
  "JSXOpeningElement": [
    "name",
    "attributes"
  ],
  "JSXSpreadAttribute": [
    "argument"
  ],
  "JSXText": [],
  "JSXFragment": [
    "openingFragment",
    "children",
    "closingFragment"
  ],
  "JSXOpeningFragment": [],
  "JSXClosingFragment": [],
  "Noop": [],
  "Placeholder": [],
  "V8IntrinsicIdentifier": [],
  "ArgumentPlaceholder": [],
  "BindExpression": [
    "object",
    "callee"
  ],
  "ImportAttribute": [
    "key",
    "value"
  ],
  "Decorator": [
    "expression"
  ],
  "DoExpression": [
    "body"
  ],
  "ExportDefaultSpecifier": [
    "exported"
  ],
  "RecordExpression": [
    "properties"
  ],
  "TupleExpression": [
    "elements"
  ],
  "DecimalLiteral": [],
  "ModuleExpression": [
    "body"
  ],
  "TopicReference": [],
  "PipelineTopicExpression": [
    "expression"
  ],
  "PipelineBareFunction": [
    "callee"
  ],
  "PipelinePrimaryTopicReference": [],
  "TSParameterProperty": [
    "parameter"
  ],
  "TSDeclareFunction": [
    "id",
    "typeParameters",
    "params",
    "returnType"
  ],
  "TSDeclareMethod": [
    "decorators",
    "key",
    "typeParameters",
    "params",
    "returnType"
  ],
  "TSQualifiedName": [
    "left",
    "right"
  ],
  "TSCallSignatureDeclaration": [
    "typeParameters",
    "parameters",
    "typeAnnotation"
  ],
  "TSConstructSignatureDeclaration": [
    "typeParameters",
    "parameters",
    "typeAnnotation"
  ],
  "TSPropertySignature": [
    "key",
    "typeAnnotation"
  ],
  "TSMethodSignature": [
    "key",
    "typeParameters",
    "parameters",
    "typeAnnotation"
  ],
  "TSIndexSignature": [
    "parameters",
    "typeAnnotation"
  ],
  "TSAnyKeyword": [],
  "TSBooleanKeyword": [],
  "TSBigIntKeyword": [],
  "TSIntrinsicKeyword": [],
  "TSNeverKeyword": [],
  "TSNullKeyword": [],
  "TSNumberKeyword": [],
  "TSObjectKeyword": [],
  "TSStringKeyword": [],
  "TSSymbolKeyword": [],
  "TSUndefinedKeyword": [],
  "TSUnknownKeyword": [],
  "TSVoidKeyword": [],
  "TSThisType": [],
  "TSFunctionType": [
    "typeParameters",
    "parameters",
    "typeAnnotation"
  ],
  "TSConstructorType": [
    "typeParameters",
    "parameters",
    "typeAnnotation"
  ],
  "TSTypeReference": [
    "typeName",
    "typeParameters"
  ],
  "TSTypePredicate": [
    "parameterName",
    "typeAnnotation"
  ],
  "TSTypeQuery": [
    "exprName",
    "typeParameters"
  ],
  "TSTypeLiteral": [
    "members"
  ],
  "TSArrayType": [
    "elementType"
  ],
  "TSTupleType": [
    "elementTypes"
  ],
  "TSOptionalType": [
    "typeAnnotation"
  ],
  "TSRestType": [
    "typeAnnotation"
  ],
  "TSNamedTupleMember": [
    "label",
    "elementType"
  ],
  "TSUnionType": [
    "types"
  ],
  "TSIntersectionType": [
    "types"
  ],
  "TSConditionalType": [
    "checkType",
    "extendsType",
    "trueType",
    "falseType"
  ],
  "TSInferType": [
    "typeParameter"
  ],
  "TSParenthesizedType": [
    "typeAnnotation"
  ],
  "TSTypeOperator": [
    "typeAnnotation"
  ],
  "TSIndexedAccessType": [
    "objectType",
    "indexType"
  ],
  "TSMappedType": [
    "typeParameter",
    "nameType",
    "typeAnnotation"
  ],
  "TSLiteralType": [
    "literal"
  ],
  "TSExpressionWithTypeArguments": [
    "expression",
    "typeParameters"
  ],
  "TSInterfaceDeclaration": [
    "id",
    "typeParameters",
    "extends",
    "body"
  ],
  "TSInterfaceBody": [
    "body"
  ],
  "TSTypeAliasDeclaration": [
    "id",
    "typeParameters",
    "typeAnnotation"
  ],
  "TSInstantiationExpression": [
    "expression",
    "typeParameters"
  ],
  "TSAsExpression": [
    "expression",
    "typeAnnotation"
  ],
  "TSSatisfiesExpression": [
    "expression",
    "typeAnnotation"
  ],
  "TSTypeAssertion": [
    "typeAnnotation",
    "expression"
  ],
  "TSEnumDeclaration": [
    "id",
    "members"
  ],
  "TSEnumMember": [
    "id",
    "initializer"
  ],
  "TSModuleDeclaration": [
    "id",
    "body"
  ],
  "TSModuleBlock": [
    "body"
  ],
  "TSImportType": [
    "argument",
    "qualifier",
    "typeParameters"
  ],
  "TSImportEqualsDeclaration": [
    "id",
    "moduleReference"
  ],
  "TSExternalModuleReference": [
    "expression"
  ],
  "TSNonNullExpression": [
    "expression"
  ],
  "TSExportAssignment": [
    "expression"
  ],
  "TSNamespaceExportDeclaration": [
    "id"
  ],
  "TSTypeAnnotation": [
    "typeAnnotation"
  ],
  "TSTypeParameterInstantiation": [
    "params"
  ],
  "TSTypeParameterDeclaration": [
    "params"
  ],
  "TSTypeParameter": [
    "constraint",
    "default"
  ]
};

