import { VISITOR_KEYS as B_VISITOR_KEYS } from "@babel/types";
import fs from "node:fs/promises";

export const VISITOR_KEYS = {...B_VISITOR_KEYS};

VISITOR_KEYS.DoWhileStatement = ["test", "body"];

const FILE = `
// WARNING: generated by dump_visitor_keys.mjs, do not edit directly

// babel changed the order at some version, but we need to keep the old one for now
export const VISITOR_KEYS = ${JSON.stringify(VISITOR_KEYS, null, 2)};

`;

await fs.writeFile("src/v2/visitor_keys.js", FILE);
